name: Deploy Backend Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend-go/**"
  pull_request:
    paths:
      - "backend-go/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod download
        working-directory: backend-go

      - name: Run tests
        run: go test ./... -v
        working-directory: backend-go
  build-push:
    runs-on: ubuntu-latest
    needs: ["test"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build Docker image
        run: docker build -t backend-go:latest .
        working-directory: backend-go
      
      - name: Get short SHA
        id: vars
        run: echo "SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: backend-go
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/backend-go:${{ steps.vars.outputs.SHA_SHORT }} \
            .

      - name: Push Docker image
        working-directory: backend-go
        run: |
          docker push ghcr.io/${{ github.repository }}/backend-go:${{ steps.vars.outputs.SHA_SHORT }}

  deploy:
    runs-on: ubuntu-latest
    needs: ["build-push"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - uses: imranismail/setup-kustomize@v2
      
    - name: Get short SHA
      id: vars
      run: echo "SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Edit manifest
      working-directory: backend-go/deployment/production
      run: |
        kustomize edit set image ghcr.io/${{ github.repository }}=ghcr.io/${{ github.repository }}/backend-go:${{ steps.vars.outputs.SHA_SHORT }}

    - name: Build manifest
      working-directory: backend-go/deployment/production
      run: |
        kubectl kustomize .

    - name: Validate
      working-directory: backend-go/deployment/production
      run: |
        kubectl apply -k . --dry-run=client --validate=true