name: Deploy Backend JS

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend-js/**"
  pull_request:
    paths:
      - "backend-js/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: backend-js
        run: npm install

      - name: Run tests
        working-directory: backend-js
        run: npm test

  build-push:
    runs-on: ubuntu-latest
    needs: ["test"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Get short SHA
        id: vars
        run: echo "SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: backend-js
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/backend-js:${{ steps.vars.outputs.SHA_SHORT }} \
            .

      - name: Push Docker image
        working-directory: backend-js
        run: |
          docker push ghcr.io/${{ github.repository }}/backend-js:${{ steps.vars.outputs.SHA_SHORT }}
